language: ruby
cache: bundler
addons:
env:
  global:
    - AWS_REGION=ap-southeast-1
    - CC_TEST_REPORTER_ID=dda6e39fff92f03327b728944253d3a58162a83e69a45f10918750786309a26a
    - CODECOV_TOKEN=cbfe3a70-5a7b-49c6-87d9-a955ec96900e
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - gem install bundler
before_script:
  - ./cc-test-reporter before-build
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  - provider: elasticbeanstalk
    region: ap-southeast-1
    app: somleng-adhearsion
    env: somleng-adhearsion-webserver
    bucket_name: deploy.somleng.org
    on:
      repo: somleng/somleng
      branch: master
