language: ruby
cache: bundler
services:
- docker
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
  - AWS_REGION=ap-southeast-1
  - CC_TEST_REPORTER_ID=dda6e39fff92f03327b728944253d3a58162a83e69a45f10918750786309a26a
  - CODECOV_TOKEN=cbfe3a70-5a7b-49c6-87d9-a955ec96900e
  # AWS Credentials
  - secure: VehVchZV3gPboMqvMBsiFLqDvwFaFI1fPCWiwMsWDvh2y150jhDY3SBfSa25gSbfbJXb8Coyg+NBpCeHwZssoFXRd+3Ve7FTXasdHcHmxSkuuIGfY+iWWL4dfWgnB6k/A9ksGESUMsdHd7U4esC8CLlUDSsHYlbybYJZFCQKDLsqfpM+rFLhGlmCJknH6ewlgDOjwSjCYPjAPiba/TOIkHX6o0Q7rdZk/NvxHOg7klSTkr6YhCqp+jtkwSQhAoB3A6ZolbXCtoELkpzIDUkqTT1HUFU9p3+ZxHDxts7hcfJm6LYkA8O46Rq08ZK4SyWY3CkDdOi+YEIRdWSZnfSLD6aOfJhabIyHSc0g8hpD8fDo//nayImG2JNtFYcbs5rqffAbitv3w3wDjA5DLLMOLe05bJHqGw5BlVDwJRKqRIn16Ty7Ihzj6NLKqD87O3PBbpNbtwOWLdBBqYpi9i91G2gpBwu7fJRsh7r1uBLDmlCt+GIcuEsC2k+nKO1S1bv2TZMrIW8OkSyI6WobYXcgpUS7n8HnTEt0a+of6bpgmo1b6p6xGjh8oTD2MVQ7HCBvxp8iH9ZcosCgDPR446hheXMfA4EnwrFbpJpMUzrpX3rr4vjYQ9VFUKGMiI1dmJVmx4BUE7pwvkUq1RDZ1fnPOgL0vk7B9DFESg0IpQSMRpw=
  # Docker Credentials
  - secure: zILKZ5GsYfZVq0u+qu51hDsujO1RKRVXFq7J8qF7mloAPY9J7Lh+2HJW/7haK5FTlT8kCYsZyEGJ6z6y9LmOIBumq+hKygqkLa5CiyC7Cd2Tmik5t2KDWYqvK59B5DlEy+JdFNlkdj3Hh9yH5+g5u9/PTdZs8vM216z/Olo8rYAZnRLw40FD40UggzmKJk/Tj9FwWb313dxlYT+oT564BUt2fd1H2fglkGtZWnRGNCN1zPhFPAd6HH5+KJvcvNmMoV6oRK6dmOi+zx63RXswc6TUUgI4BYz2Ctrq6azpQrwpkqeo0Td/ctH1lhMtbit2qTErLPm87VMHjH3Begmkecbir2RJ1sEDMyNisfdNlIv/Gsu1T+qXeM8VZeoArWYVBegxZSk4rqEFq3UvxzoyO+DoUQI/1jlRDFwqFeeCIO3cvo32fvz2DHI29bn4o0I3WAqbD1pEUhTaVgg2UzC0D8kE7arEOuBW4yiitMAT1G3fbl1d1jWyCkvw93jZxZtG5QT/9Neu9/K5edwrU+YDrf9H8pIJIfAvs3dubLRphxhAOmLXnICoFf8vvjC2MkpkUT6vl/cuw7R1JrO4Vkwt9Lzx41QLlZXx5l/wzPHf2j/0h/e2734jDgm41Xg+GwCpGJ66xiw+AQYn1A88o8yx52L3sxyzv8LYRd3DMn/PNCk=
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- gem install bundler
before_script:
- "./cc-test-reporter before-build"
after_success:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t somleng/somleng-adhearsion:latest "https://github.com/$TRAVIS_REPO_SLUG.git#$TRAVIS_BRANCH"
- docker push somleng/somleng-adhearsion
deploy:
- provider: elasticbeanstalk
  app: somleng-adhearsion
  env: somleng-adhearsion-webserver
  region: ap-southeast-1
  bucket_name: deploy.somleng.org
  on:
    branch: master
